In [1]:
from mtga_viz.ext.database_manipulation import *
from mtga_viz.ext.stats import *


df = numbers_to_df(path = "../data/win_loss_mtg_ds.numbers")

In [2]:
get_deck_summary(df, 'Energy', granularity=1)

,deck,share_pct_in_arch,share_rad_in_arch,count,wr,wr_low,wr_high
0,UW Energy,15.38,0.97,2,0.0,0.0,65.8
1,WR Energy,38.46,2.42,5,60.0,23.1,88.2
2,WRB Energy,46.15,2.90,6,33.3,9.7,70.0

In [3]:
get_archetype_summary(df, granularity=9)

,archetype,count,share_pct,share_rad,wr,wr_low,wr_high,2-0,2-1,1-2,0-2
0,Aggro,15,17.24,1.08,73.3,48.0,89.1,7,4,1,3
1,Blue Combo,22,25.29,1.59,72.7,51.8,86.8,11,5,6,0
2,Energy,13,14.94,0.94,38.5,17.7,64.5,4,1,5,3
3,Fast Combo,10,11.49,0.72,90.0,59.6,98.2,4,5,1,0
4,Rogue,13,14.94,0.94,69.2,42.4,87.3,6,3,1,3
5,Tempo,14,16.09,1.01,71.4,45.4,88.3,8,2,3,1

In [4]:

pepe=get_tricks(df)
pepe

       tricks  numbers
0  B_Finisher        5
1       DS_DD        2
2   B_Removal        2
3       DD_MS        1