In [1]:
import pandas as pd
from mtga_viz import *
from archetype_definition import dictionaries

In [2]:
# Loading the collected data
df = pd.read_csv('../data/metagame_challenge/challenge_test_file.csv')
df_clean= clean_raw_csv(df, user_deck_col='user_deck', oppo_deck_col='oppo_deck')
df_w_extra_columns = create_new_columns(
    df_clean, 
    time_col='message_time_stamp',
    interval_window=1,
    run_col='run_result', 
    source_cols=['user_deck', 'oppo_deck'], 
    keyword_dict=dictionaries, 
    new_cols=['user_deck_arch', 'oppo_deck_arch'], 
    def_tag='other')

df_w_extra_columns.head(40)

,message_time_stamp,user_name,run_result,user_deck,oppo_deck,result_vs_oppo,user_deck_arch,oppo_deck_arch
0,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur sneak and show,2-0,aggro,blue_combo
1,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur tempo,2-0,aggro,tempo
2,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono g landfall,2-0,aggro,other
3,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono b stompy,2-0,aggro,stompy
4,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,wbr energy,1-2,aggro,aggro
5,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,mono b stompy,2-1,aggro,stompy
6,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,casual,2-0,aggro,other
7,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ub reanimator,2-0,aggro,blue_combo
8,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ub tempo,2-1,aggro,tempo
9,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ur sneak and show,2-0,aggro,blue_combo
10,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,eldrazi stompy,2-1,aggro,stompy
11,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ub tempo,2-0,aggro,tempo
12,2026-05-09T00:33:56.076000+00:00,cvc42,2-1,wr energy,ubg tempo,2-0,aggro,tempo
13,2026-05-09T00:33:56.076000+00:00,cvc42,2-1,wr energy,wbr energy,2-0,aggro,aggro
14,2026-05-09T00:33:56.076000+00:00,cvc42,2-1,wr energy,wub tempo,1-2,aggro,tempo
15,2026-05-09T01:04:44.647000+00:00,greasypeezy,2-1,wr energy,ur tempo,2-0,aggro,tempo
16,2026-05-09T01:04:44.647000+00:00,greasypeezy,2-1,wr energy,wu tempo,2-0,aggro,tempo
17,2026-05-09T01:04:44.647000+00:00,greasypeezy,2-1,wr energy,ub tempo,1-2,aggro,tempo
18,2026-05-09T01:07:55.072000+00:00,zachrobotzach,3-1,bg bonds,bye,2-0,aggro,other
19,2026-05-09T01:07:55.072000+00:00,zachrobotzach,3-1,bg bonds,bye,2-0,aggro,other
20,2026-05-09T01:07:55.072000+00:00,zachrobotzach,3-1,bg bonds,eldrazi stompy,2-1,aggro,stompy
21,2026-05-09T01:07:55.072000+00:00,zachrobotzach,3-1,bg bonds,wbr energy,0-2,aggro,aggro
22,2026-05-09T01:13:08.791000+00:00,fritts4226,1-1,ub tempo,bye,2-0,tempo,other
23,2026-05-09T01:13:08.791000+00:00,fritts4226,1-1,ub tempo,wbr energy,0-2,tempo,aggro
24,2026-05-09T01:52:14.893000+00:00,zhorebba_61116,3-1,wbr energy,bye,2-0,aggro,other
25,2026-05-09T01:52:14.893000+00:00,zhorebba_61116,3-1,wbr energy,bye,2-1,aggro,other
26,2026-05-09T01:52:14.893000+00:00,zhorebba_61116,3-1,wbr energy,mono r storm,2-1,aggro,other
27,2026-05-09T01:52:14.893000+00:00,zhorebba_61116,3-1,wbr energy,ubg tempo,1-2,aggro,tempo
28,2026-05-09T02:12:30.692000+00:00,greasypeezy,3-1,ub tempo,wug nadu,2-0,tempo,blue_combo
29,2026-05-09T02:12:30.692000+00:00,greasypeezy,3-1,ub tempo,bye,2-0,tempo,other
30,2026-05-09T02:12:30.692000+00:00,greasypeezy,3-1,ub tempo,ur tempo,2-1,tempo,tempo
31,2026-05-09T02:12:30.692000+00:00,greasypeezy,3-1,ub tempo,mono r burn,0-2,tempo,aggro
32,2026-05-09T02:13:10.406000+00:00,gark314,1-1,br breach,br burn,2-0,fast_combo,aggro
33,2026-05-09T02:13:10.406000+00:00,gark314,1-1,br breach,ur tempo,1-2,fast_combo,tempo
34,2026-05-09T02:18:53.882000+00:00,aller3189,3-1,brg goyfs,bye,2-0,midrange,other
35,2026-05-09T02:18:53.882000+00:00,aller3189,3-1,brg goyfs,mono b stompy,2-0,midrange,stompy
36,2026-05-09T02:18:53.882000+00:00,aller3189,3-1,brg goyfs,wub control,2-0,midrange,control
37,2026-05-09T02:18:53.882000+00:00,aller3189,3-1,brg goyfs,br burn,1-2,midrange,aggro
38,2026-05-09T02:48:22.829000+00:00,gark314,1-1,br breach,ur tempo,2-1,fast_combo,tempo
39,2026-05-09T02:48:22.829000+00:00,gark314,1-1,br breach,mono r prowess,1-2,fast_combo,aggro

In [3]:
# This table will show you, for each deck in user_deck (or each archetype in user_deck_arch), the total amount of games, the wr with its error and the confidence level based on the amount of games.
get_table_wr_error(df_w_extra_columns, result_col='result_vs_oppo', study_col='user_deck')

                user_deck  matches_played    wr  wr_low  wr_high confidence
38             wbr energy             526  83.5    80.0     86.4       high
4                 br burn             136  69.9    61.7     76.9       high
26          ub reanimator             125  79.2    71.3     85.4       high
28               ub tempo             112  68.8    59.7     76.6       high
34      ur sneak and show             104  79.8    71.1     86.4       high
11         eldrazi stompy             104  76.9    68.0     84.0       high
35               ur tempo              90  64.4    54.2     73.6       high
27            ub shredder              84  85.7    76.7     91.6       high
30             ubg shadow              66  75.8    64.2     84.5       high
39              wr energy              62  75.8    63.8     84.8       high
31            ur affinity              59  86.4    75.5     93.0       high
0                bg bonds              58  74.1    61.6     83.7       high
2                br aggro              49  79.6    66.4     88.5     medium
33             ur prowess              39  84.6    70.3     92.8     medium
24             ub control              37  81.1    65.8     90.5     medium
8               brg goyfs              36  63.9    47.6     77.5     medium
41             wub energy              35  85.7    70.6     93.7     medium
16            mono r burn              32  62.5    45.3     77.1     medium
12           mono b aggro              31  80.6    63.7     90.8     medium
37              urg tempo              30  73.3    55.6     85.8        low
20          mono r stompy              22  72.7    51.8     86.8        low
14            mono b scam              16  75.0    50.5     89.8        low
23               rg lands              12  75.0    46.8     91.1        low
3               br breach              12  50.0    25.4     74.6        low
32                ur burn              10  80.0    49.0     94.3   very low
21          mono w humans              10  40.0    16.8     68.7   very low
17  mono r eldrazi stompy               9  77.8    45.3     93.7   very low
42        wub necro sorin               7  85.7    48.7     97.4   very low
44            wur control               6  83.3    43.6     97.0   very low
13      mono b reanimator               6  66.7    30.0     90.3   very low
1                bg lands               5  80.0    37.6     96.4   very low
6                br goyfs               4  50.0    15.0     85.0   very low
45              wur tempo               4  75.0    30.1     95.4   very low
19         mono r prowess               4  75.0    30.1     95.4   very low
22     pensive frog combo               3  66.7    20.8     93.9   very low
40               wu tempo               3  66.7    20.8     93.9   very low
43               wug nadu               3  66.7    20.8     93.9   very low
25                ub mill               3  66.7    20.8     93.9   very low
15           mono r aggro               2  50.0     9.5     90.5   very low
9          brg reanimator               2  50.0     9.5     90.5   very low
7           br moonshadow               2  50.0     9.5     90.5   very low
36              urg beans               1   0.0     0.0     79.3   very low
29                    ubg               1   0.0     0.0     79.3   very low
5              br goblins               1   0.0     0.0     79.3   very low
18         mono r goblins               1   0.0     0.0     79.3   very low
10           cavern goyfs               1   0.0     0.0     79.3   very low

In [4]:
# This table will show you Korae's shared table (w/o the win rate)
get_table_runs(df_w_extra_columns, user_deck_col='user_deck', run_col='run_result')

,user_deck_arch,user_deck,total_runs,games_played,0_win,1_win,2_win,3_win,4_win,5_win,6_win,7_win
0,aggro,wbr energy,139,611,11,19,23,24,11,15,15,21
1,aggro,br burn,45,138,15,7,9,4,1,2,3,4
2,tempo,ub tempo,36,123,7,4,8,8,4,3,2,0
3,tempo,ur tempo,35,99,7,7,8,11,2,0,0,0
4,blue_combo,ub reanimator,33,134,2,3,10,7,1,7,1,2
5,stompy,eldrazi stompy,29,106,1,6,11,2,5,1,0,3
6,blue_combo,ur sneak and show,25,102,2,6,0,7,4,0,0,6
7,tempo,ubg shadow,17,66,0,6,2,2,4,1,1,1
8,aggro,ub shredder,16,84,0,1,2,3,2,2,2,4
9,aggro,bg bonds,16,58,2,2,5,3,0,3,0,1
10,aggro,wr energy,15,62,2,1,3,0,7,0,2,0
11,midrange,brg goyfs,13,36,4,2,2,3,2,0,0,0
12,aggro,ur affinity,13,63,0,2,4,0,0,2,0,5
13,aggro,mono r burn,12,32,6,2,0,0,2,2,0,0
14,aggro,br aggro,12,49,2,1,1,4,0,2,0,2
15,tempo,urg tempo,8,30,0,1,3,2,1,1,0,0
16,aggro,ur prowess,8,39,0,2,0,0,3,1,0,2
17,aggro,wub energy,8,37,0,2,0,3,0,0,0,3
18,control,ub control,7,37,0,0,0,2,1,4,0,0
19,fast_combo,br breach,6,12,1,4,1,0,0,0,0,0
20,stompy,mono r stompy,6,22,0,1,2,2,0,1,0,0
21,aggro,mono w humans,6,10,2,4,0,0,0,0,0,0
22,aggro,mono b aggro,6,31,0,0,0,0,5,1,0,0
23,stompy,mono b scam,5,16,0,3,1,0,0,0,0,1
24,midrange,rg lands,3,12,0,0,0,3,0,0,0,0
25,midrange,cavern goyfs,2,2,2,0,0,0,0,0,0,0
26,stompy,mono r eldrazi stompy,2,9,0,0,0,1,1,0,0,0
27,aggro,ur burn,2,10,0,0,0,0,2,0,0,0
28,other,mono b reanimator,2,6,0,0,2,0,0,0,0,0
29,midrange,br goyfs,2,4,0,2,0,0,0,0,0,0
30,other,brg reanimator,1,2,0,1,0,0,0,0,0,0
31,control,wur control,1,6,0,0,0,0,0,1,0,0
32,blue_combo,wug nadu,1,3,0,0,1,0,0,0,0,0
33,fast_combo,wub necro sorin,1,7,0,0,0,0,0,0,1,0
34,aggro,br goblins,1,1,1,0,0,0,0,0,0,0
35,tempo,wu tempo,1,3,0,0,1,0,0,0,0,0
36,tempo,br moonshadow,1,2,0,1,0,0,0,0,0,0
37,blue_combo,ub mill,1,3,0,0,1,0,0,0,0,0
38,control,urg beans,1,1,1,0,0,0,0,0,0,0
39,midrange,bg lands,1,5,0,0,0,0,1,0,0,0
40,aggro,mono r aggro,1,2,0,1,0,0,0,0,0,0
41,aggro,mono r goblins,1,1,1,0,0,0,0,0,0,0
42,other,ubg,1,1,1,0,0,0,0,0,0,0
43,aggro,mono r prowess,1,4,0,0,0,1,0,0,0,0
44,other,pensive frog combo,1,3,0,0,1,0,0,0,0,0
45,tempo,wur tempo,1,4,0,0,0,1,0,0,0,0

In [5]:
# This simple table is a quick summary with all contributing players, total games, amount of runs, event duration and # of every type of run
get_table_event_summary(df_w_extra_columns)

players             119.0
runs                545.0
games              2090.0
overall_winrate      76.6
0-1                  70.0
1-1                  91.0
2-1                 101.0
3-1                  93.0
4-1                  59.0
5-1                  49.0
6-1                  27.0
7-0                  55.0
event_duration       72.0
dtype: float64

In [6]:
# This function can be a little bit strange without proper plotting, but it will basically tell you how the share of those N most used decks fluctuates every hour along the event duration. 
get_window_deck_table(df_w_extra_columns, top_n=12)

NameError: name 'get_window_deck_table' is not defined