In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().resolve().parent   # adjust if notebook is nested deeper
sys.path.insert(0, str(project_root))

In [2]:
import pandas as pd
from mtga_viz.core.database_manipulation import clean_raw_csv, explore_most_played_decks

In [3]:
df = pd.read_csv('../data/metagame_challenge/challenge_test_file.csv')

In [4]:
df_test= clean_raw_csv(df, user_deck_col='user_deck', oppo_deck_col='oppo_deck')
df_test.head()

,message_time_stamp,user_name,run_result,user_deck,oppo_deck,result_vs_oppo
0,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur sneak and show,2-0
1,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur tempo,2-0
2,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono g landfall,2-0
3,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono b stompy,2-0
4,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,wbr energy,1-2

In [5]:
most_played_decks, common_deck_counting = explore_most_played_decks(df, 'user_deck', 'oppo_deck')

In [6]:
common_deck_counting

                      user_deck  oppo_deck
WRB Energy                  410        176
UB Reanimator               115         88
UB Tempo                    107        183
BR Burn                      86         21
Eldrazi Stompy               83         50
UR Tempo                     76        114
Izzet Sneak and Show         54         34
UB Shredder                  48          2
BG Bonds                     35          4
UR Affinity                  28         21
BR Aggro                     22          6
UB Control                   21          1
R Burn                       17         15
B Scam                       16          1
BRG Goyfs                    16          1
UR Prowess                   15          3
BR Breach                    12         11
URG Tempo                    12          3
WUB Energy                   12          5
B Aggro                      10          1
mono r stompy                 9          6
R Eldrazi Stompy              9          1
RW Energy                     8          6
UWB Necro Sorin               7          5
WR Energy                     7         25
B Reanimator                  6          7
eldrazi Stompy                6          1
BR burn                       4          4
Mono R Prowess                4          1
R Stompy                      4          5
RG Lands                      4          3
GB bonds                      3          1
UWG Nadu                      3          1
Mono R Stompy                 3          6
WU Tempo                      3          3
UB Mill                       3          2
rw energy                     2          2
RUG Tempo                     2          2
mono red stompy               2          7
BR Moonshadow                 2          4
BR Goyfs                      2          1
BUG                           1          2
BR Goblins                    1          2
R Goblins                     1          2

In [7]:
from mtga_viz.core.database_manipulation import create_new_columns


TEMPO = ['tempo', 'shadow']
AGGRO = ['energy', 'aggro', 'bonds']
BLUE_COMBO = ['ub reanimator', 'show and tell', 'sneak and show']
FAST_COMBO = ['breach', 'sorin', 'muxus']
CONTROL = ['control']
STOMPY = ['stompy', 'prison']
MIDRANGE = ['goyf']

dictionaries = {'tempo': TEMPO, 
                'aggro' : AGGRO, 
                'blue_combo': BLUE_COMBO, 
                'fast_combo':FAST_COMBO,
                'stompy': STOMPY,
                'control': CONTROL,
                'midrange': MIDRANGE}

In [8]:
df_caca, length_event, intervals, amount_trophies, normalised_runs = create_new_columns(
    df_test, 'message_time_stamp', 
    interval_window=1, 
    run_col='run_result', 
    source_cols=['user_deck', 'oppo_deck'], 
    keyword_dict=dictionaries, 
    new_cols=['user_deck_arch', 'oppo_deck_arch'], 
    def_tag='other')

In [9]:
normalised_runs

run
0-1     47.0
1-1    128.0
2-1    121.0
3-1     85.0
4-1     43.0
5-1     41.0
6-1     22.0
7-0     32.0
Name: normalized_count, dtype: float64

In [10]:
df_caca

,message_time_stamp,user_name,run_result,user_deck,oppo_deck,result_vs_oppo,time_window,user_deck_arch,oppo_deck_arch,is_trophy
0,2026-05-09 00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur sneak and show,2-0,0,aggro,blue_combo,no
1,2026-05-09 00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur tempo,2-0,0,aggro,tempo,no
2,2026-05-09 00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono g landfall,2-0,0,aggro,other,no
3,2026-05-09 00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono b stompy,2-0,0,aggro,stompy,no
4,2026-05-09 00:08:13.889000+00:00,greasypeezy,4-1,wr energy,wbr energy,1-2,0,aggro,aggro,no
...,...,...,...,...,...,...,...,...,...,...
1400,2026-05-11 21:30:05.012000+00:00,pliny_theelder,5-1,bg bonds,mono u flash,2-0,69,aggro,other,no
1401,2026-05-11 21:30:05.012000+00:00,pliny_theelder,5-1,bg bonds,ub reanimator,2-0,69,aggro,blue_combo,no
1402,2026-05-11 21:30:05.012000+00:00,pliny_theelder,5-1,bg bonds,bye,2-0,69,aggro,other,no
1403,2026-05-11 21:30:05.012000+00:00,pliny_theelder,5-1,bg bonds,ur tempo,2-0,69,aggro,tempo,no
1404,2026-05-11 21:30:05.012000+00:00,pliny_theelder,5-1,bg bonds,mono r storm,0-2,69,aggro,other,no